# Generated by Django 3.2.9 on 2022-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIF', '0003_auto_20220223_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='coordenadas',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
