# Generated by Django 3.2.9 on 2022-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIF', '0004_alter_inmueble_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='coordenadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
