# Generated by Django 3.2.9 on 2022-03-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BIF', '0006_auto_20220329_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='coordenadas',
            new_name='coordenates',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='archivo',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='licence',
            name='id_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='BIF.property'),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='id_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='BIF.property'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='BIF.property'),
        ),
    ]
