# Generated by Django 3.2.9 on 2022-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('numero_predial', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('numero_predial_nacional', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('notaria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('num_escritura', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('uso', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('ciudadela_educativa', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='staticfiles/files')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
    ]
